/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


public class App {

    public static void main(String[] args) {
        Student a = new Student("joe",3.5,"math");
        System.out.println(a);
    }
}
